config/routes.rb
NewsAgg::Application.routes.draw do
  root:to => "post#index"
  controller :post do
    get "show/:id"=>:show, :as => :show
    get "show_latest/:id"=>:show_latest, :as => :show_latest
    get "category/:id"=>:category, :as => :category
  end

end

app/models/post.rb
class Post < ActiveRecord::Base

end

app/models/source.rb
class Source < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/post_controller.rb
require 'crawler_engine'
class PostController < ApplicationController
  before_filter :fetch_categories, :only=>[:index,:category]

  def index
    #CrawlerEngine.start
    session[:category]=0
    @posts = Post.find_by_sql("select * from posts order by published_at desc limit 10 ")
  end

  def show
    arry=params[:id].split("&")
    if arry[0].to_s=="0"
      @posts = Post.find_by_sql("select * from posts where published_at < '#{arry[1]}' order by published_at desc limit 10 ")
    else
      session[:category]=arry[0]
      @posts = Post.find_by_sql("select * from posts where published_at < '#{arry[1]}' and category='#{arry[0]}' order by published_at desc limit 10 ")
    end
  end

  def show_latest
    arry=params[:id].split("&")
    if arry[0].to_s=="0"
      @posts = Post.find_by_sql("select * from posts where published_at > '#{arry[1]}' order by published_at desc")
    else
      session[:category]=arry[0]
      @posts = Post.find_by_sql("select * from posts where published_at > '#{arry[1]}' and category='#{arry[0]}' order by published_at desc")
    end
  end

  def category
    session[:category]=params[:id]
    @posts = Post.find_by_sql("select * from posts where category='#{session[:category]}' order by published_at desc limit 10 ")
  end

  private
  def fetch_categories
    @categories = Source.select("DISTINCT(category)")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def highlight_home
    if session[:category]==0
      "active"
    end
  end

  def highlight_nav(cate)
    if session[:category]== cate.category
      "active"
    else
      ""
    end
  end
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eeveryday News|世界就在你身边，这一刻！ </title>
    <link rel="shortcut icon" type="image/png" href="favicon.ico" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <%= stylesheet_link_tag 'bootstrap.min.css', :media=>'screen' %>
    <%= stylesheet_link_tag 'global.css', :media=>'screen' %>
    <%= stylesheet_link_tag 'jflow.css', :media=>'screen' %>
    <%= javascript_include_tag 'jquery.min-1.5.1.js' %>
    <%= javascript_include_tag 'application.js' %>
    <%= javascript_include_tag 'jflow.js' %>
    <%= csrf_meta_tag %>
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-23115957-5']);
      _gaq.push(['_trackPageview']);

      (function() {
       var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
       ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
       var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
       })();
</script>

<script type="text/javascript">
  $(document).ready(function(){
      $("#myController").jFlow({
controller: ".jFlowControl", // must be class, use . sign
slideWrapper : "#jFlowSlider", // must be id, use # sign
slides: "#mySlides",  // the div where all your sliding divs are nested in
selectedWrapper: "jFlowSelected",  // just pure text, no sign
effect: "flow", //this is the slide effect (rewind or flow)
width: "100%",  // this is the width for the content-slider
height: "300px",  // this is the height for the content-slider
duration: 200,  // time in milliseconds to transition one slide
pause: 300, //time between transitions
prev: ".jFlowPrev", // must be class, use . sign
next: ".jFlowNext", // must be class, use . sign
auto: true
});

      hookUpMouseEvent();
      });
</script>
      </head>
      <style type="text/css">
        body {
          padding-top: 60px;
        }
      </style>
      <body>

        <div class="topbar">
          <div class="topbar-inner">
            <div class="container-fluid">
              <%= link_to 'Everyday News {新鲜时讯}', root_path, :class=>"brand" %>
              <ul class="nav">
                <li class="<%= highlight_home%>"><%= link_to "主页", root_path%></li>
                <% @categories.each do |cate|%>
                  <li class="<%= highlight_nav(cate)%>"><%= link_to cate.category, category_path(cate.category)%></li>
                <% end %>
              </ul>
              <p class="pull-right"><a href="http://tim.everyday-cn.com">联系我们</a></p>
            </div>
          </div>
        </div>

        <%= yield %>
      </body>
    </html>

app/views/post/_preview.html.erb
<% @posts.each do |post|%>
  <div class="news-item" onclick="newsClick(this)">
    <div class="news-submit">
      <%= image_tag"news_icon.gif", :align=>"absmiddle", :class=>"favicon"%><span class="label"><%= post.site_name%></span> -
      <span><%= post.published_at.strftime("%Y-%m-%d %H:%M:%S")%></span> |
      <span class="label warning"><%= post.category%></span>
      <div class="nail">
        <% if post.thumbnail != nil&&post.thumbnail.include?("http://")%>
          <%= image_tag "../html_contents/"+post.published_at.strftime("%Y%m%d")+"/"+post.id.to_s+".png", :class=>"span1"%>
        <% end %>
      </div>
    </div>
    <div>
      <h2><%= link_to post.title, "#", :onclick=>"newsClick(this.parentNode.parentNode);return false"%> <%= link_to "[原文]", post.source,:class=>'origin', :target=>"_blank"%></h2>
      <div class="hidden-id"><%= post.id%></div>
      <div class="hidden-title"><%= post.title%></div>
      <div class="hidden-time"><%= post.published_at.strftime("%Y-%m-%d %H:%M:%S")%></div>
      <div class="hidden-time2"><%= post.published_at.strftime("%Y%m%d")%></div>
    </div>
  </div>
<% end %>

app/views/post/category.html.erb
<div class="container-fluid">
  <div class="sidebar">
    <div id="news-update" class="well">
      <p class="source-title-header">
      <span id="refresh_time" class="label notice", style="float:left;">上次更新: <%= Time.new.strftime("%H:%M")%></span>
      <span id="refreshing" style="float:left;display:none;font-size:16px;"><%= image_tag('ajax-loader.gif', :align=>"absmiddle")%> 加载最新新闻...</span>
      <span><a href="javascript:loadNew(1)">正在发生</a></span>
      </p>
    </div>
    <div class="hidden-cate"><%= session[:category]%></div>
    <div id="news-view" class="well">
      <% @posts.each do |post|%>
        <div class="news-item" onclick="newsClick(this)">
          <div class="news-submit">
            <%= image_tag"news_icon.gif", :align=>"absmiddle", :class=>"favicon"%><span class="label"><%= post.site_name%></span> -
            <span><%= post.published_at.strftime("%Y-%m-%d %H:%M:%S")%></span> |
            <span class="label warning"><%= post.category%></span>
            <div class="nail">
              <% if post.thumbnail != nil&& post.thumbnail.include?("http://")%>
                <%= image_tag "../html_contents/"+post.published_at.strftime("%Y%m%d")+"/"+post.id.to_s+".png", :class=>"span1"%>
            <% end %>
            </div>
          </div>
          <h2><%= link_to post.title, "#", :onclick=>"newsClick(this.parentNode.parentNode);return false"%> <%= link_to "[原文]", post.source,:class=>'origin', :target=>"_blank"%></h2>
          <div class="hidden-id"><%= post.id%></div>
          <div class="hidden-title"><%= post.title%></div>
          <div class="hidden-time"><%= post.published_at.strftime("%Y-%m-%d %H:%M:%S")%></div>
          <div class="hidden-time2"><%= post.published_at.strftime("%Y%m%d")%></div>
        </div>
      <% end %>
    </div>
    <div style="width:100%;height:70px;">
      <div id="loading_more" class="more_loader"><%= image_tag('ajax-loader.gif')%> 正在加载更多新闻...</div>
    </div>
  </div>

  <div class="content">
    <div id="preview_header" class="preview_header">
      <div style="float:left;"><%= image_tag 'basic_view.gif',:style=>"vertical-align:middle;"%><span style="margin-left:10px">原文阅读</span></div>
    </div>

    <div id="preview_pannel" class="preview_pannel" style="margin:0 auto">
      <table width="99%">
        <tr>
          <td id="preview_content">
            <div id="preview_loader">
              <div class='preview_loader_title'></div>
            </div>
          </td>
        </tr>
      </table>
    </div>

    <!--For first page display... -->
    <div id="intro">
      <div id="intro-wrapper">
        <h2 style="float:right;">
          世界就在你身边 <span>&middot;</span> <span style="color:#888">这一刻！</span>
        </h2>
        <div id="sliderContainer">
          <div id="mySlides">

            <% @posts.each do |post|%>
              <% if post.thumbnail!= nil&&post.thumbnail.include?("http://")%>
                <div id="slide<% post.id%>" class="slide">
                  <div class="hidden-id"><%= post.id%></div>
                  <div class="hidden-time2"><%= post.published_at.strftime("%Y%m%d")%></div>
                  <%= image_tag "../html_contents/"+post.published_at.strftime("%Y%m%d")+"/"+post.id.to_s+".png"%>
                  <div class="slideContent">
                    <h3><%= link_to post.title, "#", :onclick=>"newsClick(this.parentNode.parentNode.parentNode.parentNode);return false"%></h3>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>

          <div id="myController">
            <% @posts.each do |post|%>
              <span class="jFlowControl"><%= post.id%></span>
            <% end %>
          </div>

          <div class="jFlowPrev"></div>
          <div class="jFlowNext"></div>
        </div>

      </div>
      <div id="lower_intro">
        <p>
        <%= image_tag "quote_char.png", :style=>"height: 35px; width:40px;", :align=>"absmiddle"%>
        <span class="label important">我的工作是探索网络，发现到你最不能错过的新闻！</span></p>
      </div>
    </div>
    <!--For first page display end... -->

  </div>
</div>

app/views/post/index.html.erb
<div class="container-fluid">


  <div class="sidebar">
    <div id="news-update" class="well">
      <p class="source-title-header">
      <span id="refresh_time" class="label notice", style="float:left;">上次更新: <%= Time.new.strftime("%H:%M")%></span>
      <span id="refreshing" style="float:left;display:none;font-size:16px;"><%= image_tag('ajax-loader.gif', :align=>"absmiddle")%> 加载最新新闻...</span>
      <span><a href="javascript:loadNew(1)">正在发生</a></span>
      </p>
    </div>

    <div class="hidden-cate"><%= session[:category]%></div>
    <div id="news-view" class="well">
      <% @posts.each do |post|%>
        <div class="news-item" onclick="newsClick(this)">
          <div class="news-submit">
            <%= image_tag"news_icon.gif", :align=>"absmiddle", :class=>"favicon"%><span class="label"><%= post.site_name%></span> -
            <span><%= post.published_at.strftime("%Y-%m-%d %H:%M:%S")%></span> |
            <span class="label warning"><%= post.category%></span>
            <div class="nail">
              <% if post.thumbnail != nil&&post.thumbnail.include?("http://")%>
                <%= image_tag "../html_contents/"+post.published_at.strftime("%Y%m%d")+"/"+post.id.to_s+".png", :class=>"span1"%>
              <% end %>
            </div>
          </div>

          <h2><%= link_to post.title, "#", :onclick=>"newsClick(this.parentNode.parentNode);return false"%> <%= link_to "[原文]", post.source,:class=>'origin', :target=>"_blank"%></h2>
          <div class="hidden-id"><%= post.id%></div>
          <div class="hidden-title"><%= post.title%></div>
          <div class="hidden-time"><%= post.published_at.strftime("%Y-%m-%d %H:%M:%S")%></div>
          <div class="hidden-time2"><%= post.published_at.strftime("%Y%m%d")%></div>
        </div>
      <% end %>
    </div>
    <div style="width:100%;height:70px;">
      <div id="loading_more" class="more_loader"><%= image_tag('ajax-loader.gif')%> 正在加载更多新闻...</div>
    </div>
  </div>

  <div class="content">
    <div id="preview_header" class="preview_header">
      <div style="float:left;"><%= image_tag 'basic_view.gif',:style=>"vertical-align:middle;"%><span style="margin-left:10px">原文阅读</span></div>
    </div>

    <div id="preview_pannel" class="preview_pannel" style="margin:0 auto">
      <table width="99%">
        <tr>
          <td id="preview_content">
            <div id="preview_loader">
              <div class='preview_loader_title'></div>
            </div>
          </td>
        </tr>
      </table>
    </div>

    <!--For first page display... -->
    <div id="intro">
      <div id="intro-wrapper">
        <h2 style="float:right;">
          世界就在你身边 <span>&middot;</span> <span style="color:#888">这一刻！</span>
        </h2>
        <div id="sliderContainer">
          <div id="mySlides">

            <% @posts.each do |post|%>
              <% if post.thumbnail!= nil&&post.thumbnail.include?("http://")%>
                <div id="slide<% post.id%>" class="slide">
                  <div class="hidden-id"><%= post.id%></div>
                  <div class="hidden-time2"><%= post.published_at.strftime("%Y%m%d")%></div>
                  <img src="html_contents/<%= post.published_at.strftime("%Y%m%d")%>/<%=post.id%>.png" />
                  <div class="slideContent">
                    <h3><%= link_to post.title, "#", :onclick=>"newsClick(this.parentNode.parentNode.parentNode.parentNode);return false"%></h3>
                  </div>
                </div>
              <% end %>
            <% end %>

          </div>

          <div id="myController">
            <% @posts.each do |post|%>
              <span class="jFlowControl"><%= post.id%></span>
            <% end %>
          </div>

          <div class="jFlowPrev"></div>
          <div class="jFlowNext"></div>
        </div>

      </div>
      <div id="lower_intro">
        <p>
        <%= image_tag "quote_char.png", :style=>"height: 35px; width:40px;", :align=>"absmiddle"%>
        <span class="label important">我的工作是探索网络，发现到你最不能错过的新闻！</span></p>
      </div>
    </div>
    <!--For first page display end... -->

  </div>
</div>

app/views/post/show.js.erb
$('#news-view').append("<%= escape_javascript(render(:partial => "post/preview", :locals => {:next_posts => @posts})) %>");

app/views/post/show_latest.js.erb
$('.news-item:first').before("<%= escape_javascript(render(:partial => "post/preview", :locals => {:next_posts => @posts})) %>");